### ISSUE TITLE
IPs repeated too often

### ISSUE THREAD

**Issue by vnportnoy** [evait-security/docker-multitor#1]
Tor is supposed to have thousands of IPs in its pool but for some reason my IP used here is repeated way too often, maybe once every 20th request. 
Is this related to the number of tor instances launched at beginning or is it something else?

**Comment by FLX-0x00** [comment]
Seems to be an "issue" from multitor itself. We only provide the Dockerfile to simplify the build/running process. Please send any issues that not relating to the docker setup environment to the project that maintain the multitor code itself.

https://github.com/trimstray/multitor
